### Login
POST http://localhost:8003/api/auth/login
Content-Type: application/json

{
    "email": "ck9339701@gmail.com",
    "password": "chandan"
}


### Register User
POST http://localhost:8003/api/auth/register
Content-Type: application/json

{
    "name": "Rahul Kumar",
    "email": "rahul@example.com",
    "phone": "9876543210",
    "dateOfBirth": "1998-05-15",
    "password": "Test@123",
    "address": "MG Road",
    "city": "Bengaluru",
    "state": "Karnataka",
    "country": "India",
    "openingBalance": 10000
}


### Get Profile
GET http://localhost:8003/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGVJZCI6Miwicm9sZU5hbWUiOiJVU0VSIiwiaWF0IjoxNzkxMTk0MDgxLCJleHAiOjE3OTEyODA0ODF9.tSCg3mw24P1b0TWPxFBydJ6AB1YERVSBjridC10y5IM


### Get admin test
http://localhost:8003/api/auth/admin-test
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVJZCI6MSwicm9sZU5hbWUiOiJBRE1JTiIsImlhdCI6MTc5MTE5MzIxNiwiZXhwIjoxNzkxMjc5NjE2fQ.h0eXUl6xytg2e4YiH0xqJevHmxudihSagwu-LhPXwoM

### helmet test
GET http://localhost:8003/test